/**
 * Static map: capital city name (as returned by restcountries.com `capital`)
 * → primary international airport IATA code.
 *
 * Used to resolve a randomly picked country to a flight destination.
 * If a capital is missing here, the trip generator picks another country.
 */
export const capitalToIata: Record<string, string> = {
  // --- Europe ---
  Budapest: 'BUD',
  Paris: 'CDG',
  London: 'LHR',
  Berlin: 'BER',
  Rome: 'FCO',
  Madrid: 'MAD',
  Amsterdam: 'AMS',
  Vienna: 'VIE',
  Prague: 'PRG',
  Warsaw: 'WAW',
  Bucharest: 'OTP',
  Athens: 'ATH',
  Lisbon: 'LIS',
  Dublin: 'DUB',
  Brussels: 'BRU',
  Copenhagen: 'CPH',
  Stockholm: 'ARN',
  Oslo: 'OSL',
  Helsinki: 'HEL',
  Reykjavik: 'KEF',
  Zagreb: 'ZAG',
  Bratislava: 'BTS',
  Ljubljana: 'LJU',
  Belgrade: 'BEG',
  Sofia: 'SOF',
  Sarajevo: 'SJJ',
  Skopje: 'SKP',
  Tirana: 'TIA',
  Podgorica: 'TGD',
  Pristina: 'PRN',
  Chisinau: 'KIV',
  Kyiv: 'KBP',
  Kiev: 'KBP',
  Minsk: 'MSQ',
  Moscow: 'SVO',
  'Saint Petersburg': 'LED',
  Riga: 'RIX',
  Vilnius: 'VNO',
  Tallinn: 'TLL',
  Bern: 'ZRH',
  Zurich: 'ZRH',
  Luxembourg: 'LUX',
  Valletta: 'MLA',
  Nicosia: 'LCA',
  'Monaco': 'NCE',
  'Andorra la Vella': 'BCN',
  'San Marino': 'RMI',
  'Vatican City': 'FCO',
  'Vaduz': 'ZRH',
  Tbilisi: 'TBS',
  Yerevan: 'EVN',
  Baku: 'GYD',
  Ankara: 'ESB',
  Istanbul: 'IST',

  // --- Middle East ---
  'Abu Dhabi': 'AUH',
  Dubai: 'DXB',
  Doha: 'DOH',
  'Kuwait City': 'KWI',
  Manama: 'BAH',
  Muscat: 'MCT',
  Riyadh: 'RUH',
  Amman: 'AMM',
  Beirut: 'BEY',
  Damascus: 'DAM',
  Baghdad: 'BGW',
  Tehran: 'IKA',
  Jerusalem: 'TLV',
  'Tel Aviv': 'TLV',
  "Sana'a": 'SAH',

  // --- Asia ---
  Tokyo: 'NRT',
  Beijing: 'PEK',
  Shanghai: 'PVG',
  Seoul: 'ICN',
  Pyongyang: 'FNJ',
  Bangkok: 'BKK',
  Singapore: 'SIN',
  'Kuala Lumpur': 'KUL',
  Jakarta: 'CGK',
  Manila: 'MNL',
  Hanoi: 'HAN',
  'Ho Chi Minh City': 'SGN',
  'Phnom Penh': 'PNH',
  Vientiane: 'VTE',
  Naypyidaw: 'NYT',
  Yangon: 'RGN',
  'New Delhi': 'DEL',
  'Sri Jayawardenepura Kotte': 'CMB',
  Colombo: 'CMB',
  Kathmandu: 'KTM',
  Thimphu: 'PBH',
  Dhaka: 'DAC',
  Islamabad: 'ISB',
  Kabul: 'KBL',
  Tashkent: 'TAS',
  Astana: 'NQZ',
  'Nur-Sultan': 'NQZ',
  Bishkek: 'FRU',
  Dushanbe: 'DYU',
  Ashgabat: 'ASB',
  Ulaanbaatar: 'UBN',
  'Taipei': 'TPE',
  Male: 'MLE',
  'Bandar Seri Begawan': 'BWN',
  Dili: 'DIL',

  // --- Africa ---
  Cairo: 'CAI',
  Nairobi: 'NBO',
  Johannesburg: 'JNB',
  'Cape Town': 'CPT',
  Pretoria: 'JNB',
  Casablanca: 'CMN',
  Rabat: 'RBA',
  Tunis: 'TUN',
  Algiers: 'ALG',
  Tripoli: 'TIP',
  'Addis Ababa': 'ADD',
  Accra: 'ACC',
  Lagos: 'LOS',
  Abuja: 'ABV',
  Dakar: 'DSS',
  Abidjan: 'ABJ',
  'Yamoussoukro': 'ABJ',
  Khartoum: 'KRT',
  'Dar es Salaam': 'DAR',
  Dodoma: 'DOD',
  Kampala: 'EBB',
  Kigali: 'KGL',
  Lusaka: 'LUN',
  Harare: 'HRE',
  Luanda: 'LAD',
  Maputo: 'MPM',
  Windhoek: 'WDH',
  Gaborone: 'GBE',
  Maseru: 'MSU',
  Mbabane: 'MTS',
  Lilongwe: 'LLW',
  Antananarivo: 'TNR',
  'Port Louis': 'MRU',
  Victoria: 'SEZ',
  Bamako: 'BKO',
  Ouagadougou: 'OUA',
  Niamey: 'NIM',
  Conakry: 'CKY',
  Freetown: 'FNA',
  Monrovia: 'ROB',
  Lomé: 'LFW',
  Lome: 'LFW',
  'Porto-Novo': 'COO',
  Yaoundé: 'NSI',
  Yaounde: 'NSI',
  Libreville: 'LBV',
  Brazzaville: 'BZV',
  Kinshasa: 'FIH',
  Bangui: 'BGF',
  "N'Djamena": 'NDJ',
  Asmara: 'ASM',
  Djibouti: 'JIB',
  Mogadishu: 'MGQ',
  Bujumbura: 'BJM',

  // --- Americas ---
  'Washington, D.C.': 'IAD',
  Washington: 'IAD',
  'New York': 'JFK',
  'Los Angeles': 'LAX',
  Ottawa: 'YOW',
  Toronto: 'YYZ',
  'Mexico City': 'MEX',
  Guatemala: 'GUA',
  'Guatemala City': 'GUA',
  'San Salvador': 'SAL',
  Tegucigalpa: 'TGU',
  Managua: 'MGA',
  'San José': 'SJO',
  'San Jose': 'SJO',
  'Panama City': 'PTY',
  Havana: 'HAV',
  Kingston: 'KIN',
  'Santo Domingo': 'SDQ',
  'Port-au-Prince': 'PAP',
  Nassau: 'NAS',
  Bridgetown: 'BGI',
  'Port of Spain': 'POS',
  Bogotá: 'BOG',
  Bogota: 'BOG',
  Caracas: 'CCS',
  Quito: 'UIO',
  Lima: 'LIM',
  'La Paz': 'LPB',
  Sucre: 'SRE',
  Asunción: 'ASU',
  Asuncion: 'ASU',
  Santiago: 'SCL',
  'Buenos Aires': 'EZE',
  Montevideo: 'MVD',
  Brasília: 'BSB',
  Brasilia: 'BSB',
  'São Paulo': 'GRU',
  'Sao Paulo': 'GRU',
  Paramaribo: 'PBM',
  Georgetown: 'GEO',

  // --- Oceania ---
  Canberra: 'CBR',
  Sydney: 'SYD',
  Wellington: 'WLG',
  Auckland: 'AKL',
  Suva: 'SUV',
  'Port Moresby': 'POM',
  Honiara: 'HIR',
  'Port Vila': 'VLI',
  Apia: 'APW',
  "Nuku'alofa": 'TBU',
  Tarawa: 'TRW',
  Majuro: 'MAJ',
  Palikir: 'PNI',
  Ngerulmud: 'ROR',
  Yaren: 'INU',
  Funafuti: 'FUN',
}

/** Resolve a capital city name to an IATA code, or null if unknown. */
export function resolveIata(capital: string | undefined | null): string | null {
  if (!capital) return null
  return capitalToIata[capital.trim()] ?? null
}
